### ISSUE TITLE
правки по ДЗ

### ISSUE THREAD

**Issue by kateryna06** [DmitriyMK/DmitriyMK.github.io#1]
1. название папок желательно делать с маленькой буквы
2. название твоих стилей тоже должно быть типа: style.css, all.css но не aboutme.css
   А если у тебя добавится еще одна страница, то уже не будет логики в твоем названии ))

Т.е. файлы, классы, названия картинок - все должно нести какую-то логику, а не просто от балды 
1. вам в уроке рассказывали про то как нужно правильно прописывать font. Использовать нужно сокращенную версию в которой ты указываешь font-size, line-height, font-family
2. я писала всем в скайп про форматирование файлов, чтоб не было лишних пустых строк и т.п. Вижу пустые строки и css не отформатирован
3. твой контент не выровнен по центру
4. не хватает тени у блока
5. бекграунд у боди тоже не того цвета
6. всем ссылкам, которые ведут на другой сайт, нужно прописывать target="_blank"

**Comment by DmitriyMK** [comment]
спасибо за замечания :-). 
практически все подправил, только 
— не исправил название папки для картинки(пока не разобрался как переименовывать папки в гитхабе) 
— и не отцентрирровал контент, бо страница становится не похожа на образец. сделал отступы вместо этого.

**Comment by kateryna06** [comment]
1. то как ты отцентрировал блок - это не правильно. Если человек откроет эту страницу с большим или меньшим разрешением экрана. То он уже не будет отцентрирован. В перво уроке Олег рассказывал как это можно сделать. Посмотри, пожалуйста еще раз этот урок. 
2. Если проинспектируешь боди, http://joxi.ru/XEA40Gbs341YAb то увидишь что он по умолчанию имеет значения для маржина. А ты ему еще дополнительно задаешь верхний паддинг. Не нужно делать такую "елочку". Если ты хочешь отодвинуть сверху, то лучше уже перебить сущесвтующий дефолтный стиль.
3. с section нужно убрать высоту. А если у тебя добавится еще какая то информация. То твой текст обрежется, а нужно чтоб блок тянулся. Тут два выхода: или height заменить на min-height или на самый последний блок задать нижний отступ
4. все hr нужно поубирать и полоску добавить другим способом )) Если не догадаешься как, пиши подскажу ))
5. с ul у тебя получилась таже самая "елочка" http://joxi.ru/K823GM8SP10N2O

**Comment by kateryna06** [comment]
1. Arial, Times New Roman, Times, serif; 
   Arial - это семейство шрифтов sans-serif
   Times - семейство шрифтов serif

Не может быть два разных семеств в одном месте http://www.w3schools.com/cssref/css_websafe_fonts.asp

**Comment by DmitriyMK** [comment]
ого, сколько ёлочек я посадил, прям к новому году готовлюсь :-)  
наведу порядок в страничке вечером.

**Comment by DmitriyMK** [comment]
1. Блок отцентрирован с помощью процентов margin и padding. Я правильно сделал? 
2. Елки срублены, путем отмены дефолтного стиля margin и padding
3. height заменен на min-height
4. hr урезал. Сделал блоки "box", и вставил border-bottom. Это правильный ответ?)
5. Детская ошибка получилась, исправил на одно семейство - Arial, Helvetica, sans-serif;.

По поводу центрирования контента, вопросик маленький.
Красиво ли делать так как я тут сделал через процентные "margin" и "padding"? или лучше "text-align:center" использовать

**Comment by kateryna06** [comment]
1. сделал ты правильно, но отцентрировал ты его маржином, а не падингом. Паддинг задает тебе внутренние отступы у блока
2. ```
   border-bottom: 2px solid grey; Цвет бордеров, цвет текста или бекграунд лучше задавать в формате #fffret И ширина бордера задана не правильно.
   ```
3. http://joxi.ru/1bmoyebHDp9JAy вот эти отступы заданы не правильно. Посмотри на дизайн плиз
4. не забываем про форматирование css, html. У тебя он не совсем отформатирован.
   Нужно делать чтоб все было красиво, чтоб когда другой человек открыл твои файлы, ему было приятно работать с ними. 
5. В css стили тоже пишем так сказать "в порядке живой очереди" Т.е. все стили должны писать по порядку, а не в разброс. Сначала общие стили, а потом уже кастомные. 

А теперь к твоему вопросу про центрирование. 

Если тебе нужно отцентрировать блок, то ты ему задаешь ширину и margin:0 auto; (0 - если тебе не нужны верхние и нижние отступы)

Если тебе нужно отцентрировать контент в блоке, то тут ты используешь text-align:center

Чтобы понять разницу, ты можешь убрать свои стили маржина с блока и написать text-align:center и увидишь что происходит

Если есть вопросы - пиши

**Comment by DmitriyMK** [comment]
1. Поменял.
2. отступы сделал таким образом
   p {
   margin-left: 10px;
   }
   ul{
   margin-left: 30px;
   }
   Уместное решение, или подумать над лучшим?
3. Навел красоту в форматировании. Хотя смотрю форматирование от саблайма не всегда идет красиво. (Edit-Line-Reindent). Исправил неточности вручную(
4. После совета писать стили css стили в порядке живой очереди, поменял свой принцип стилизации. Теперь переживаю не слишком ли большое нагромаждение стилей получилось. 
   И уместно ли я использовал тэг -br- в HTML ?

**Comment by kateryna06** [comment]
1. а зачем ты задал картинке id? Он там не нужен ))
2. http://joxi.ru/lbrRqynCgJR4A1 так так так... зачем тебе столько разных классов?? 

http://joxi.ru/jnAylD6IpYde2Z Идем логическим путем, у тебя тут явных 4 блока, и 3 у которых есть бордер и которые имеют одинаковые стили. По этому тебе нужен всего лишь 1 общий класс на который ты повесишь border-top а не border-bottom чтоб его потом не обнулять для последнего блока
1. также стили http://joxi.ru/WKAx0DMsJMGlA8 тебе не нужны, ты же можешь задать больше отступ для section и у тебя не будет лишних стилей
2. br все удалить. Их использование лучше избегать, и применяются они в очень крайних случаях
3. http://joxi.ru/4DmBK5RHEwp52P этот отступ тоже лишний, ты же можешь задать боковой отступ для твоего box.
   
   А если я захочу добавить заголовок в box, то он у меня прилипнит к краю, а так, если ты задашь боковой отступ для box, то все чтобы ты не добавил не будет прилипать
4. не увидела чтоб у тебя стили были структурированы. У тебя классы перемешаны с общими стилями для тегов
5. background-color: #eeeeee; запись не ошибочная, но лучше писать сокращенно background-color: #eee; (если у нас символы одинаковые, то их можно сократить до 3х ) Так мы сокращаем размер нашего файла

**Comment by DmitriyMK** [comment]
1. Id автоматически создался в саблайме, решил что хай уж будет, может пригодится) 
2. Классы родились в результате паники (захотелось полного контроля над каждым блоком) и отсутствия логики (не смог догадаться поменять  border-bottom на border-top). 
   Уже убрал лишнее.
3. Убрал лишние стили для блоков, все в section
4. br безжалостно убраны.
5. Выполнено. Единый Padding на все стороны для box.
6.  структуру почистил, сначала стили для тегов, в конце стиль класса. 
7. класс, спасибо буду знать что так можно)

все безуспешно мучаюсь над двумя вопросами.. 
1. Задал первый блок header. Отцентрировал контент с помощью  text-align:center, но необходимо что эта часть была с отступом подобным следующим блокам "box" (padding: 3%;)
http://joxi.ru/nAyx4ByS7BzP2Z
Мне лучше создать отдельный стиль для тега "p" или отдельный div создать?
Или зацентровать только H1 и Id картинки?

2.Для вот этого блока http://joxi.ru/krDlX8vIpkbZrp согласно макета необходимо отступ сделать между номером телефона и профилем вконтакте. Так же лучше создать отдельный стиль для тега  "p" или отдельный div создать?

**Comment by kateryna06** [comment]
1. а ты куда убрал выравнивание блока по центру??? Верни )) У тебя же section сейчас не по центру стоит

а теперь к твоим вопросам. Если мучаешься взял бы в скайпе и написал и спросил. Я же не кусаюсь )))
1. Тебе нужно задать отдельный стиль для этого параграфа. И сделать это от родителся, чтоб этот стиль не применился к другим параграфам
2. Ты можешь добавить класс на этот параграф и прописать к нему отступ или обернуть 2 параграфа в див и задать ему отступ

**Comment by DmitriyMK** [comment]
Упс, вернул пропажу))
Спасибо за совет, удалось все сделать в лучшем виде))

**Comment by kateryna06** [comment]
ЗАЧЕТ
