### ISSUE TITLE
html 7-8

### ISSUE THREAD

**Issue by sergolius** [DmitriyMK/DmitriyMK.github.io#13]
1. BEM: BLOCK__ELEMENT_MODIFICATOR  
   incorrect: `.wrapper__menu > .wrapper__menu__item > .wrapper__menu__link`  
   correct: `.wrapper__menu > .wrapper__menu-item > .wrapper__menu-link`
2. Нужно сверстать адаптивно. Что бы макет был удобен для просмотра на устройствах с разным размером экрана.
3. Обратите внимание на тени шрифтов: размеры, размытие, цвет.

**Comment by DmitriyMK** [comment]
1. Спасибо за замечание, исправлю;
2. Несмотря на то что сделал отступы боковые относительно и в процентах, все равно не совсем адаптивно получился макет. Подскажите пожалуйста, для лучшей адаптивности следует сделать больше брейкпоинтов? Или перевести ширину всех блоков с px на em?

**Comment by sergolius** [comment]
1. При уменьшении экрана на странице присутствует горизонтальный скролл, этого быть не должно.
   - `.blog__content` - задана ширина которая больше ширины окна в любом бейкпоинте (кроме desktop), из-за этого появляется скролл;
   - элементы не помещаются в экран по горизонтали.
   - не стоит задавать высоту, пример классов с заданной высотой: `.prefooter__left, .prefooter__center, .prefooter__right`

Используйте px они проще в понимании и более предсказуемы.

С начала начнем с:
- избавимся от горизонтального скролла;
- учитывая, что существует великое множество экранов с разным разрешением: проверяем верстку начиная наибольшего доступного (fullHD - 1920 width) и постепенно уменьшаем размер окна браузера. Получится попиксельное уменьшение размера окна браузера. Таким образом проверим верстку на "всех" размерах;
- обращаем внимание на положение блоков в разных брейкпоинтах (на мокапах);
- не задаем высоту блокам, в которых может изменяться количество контента;

Далее:
- обращаем внимание на размещение блоков, контента, иконок и т.д. с пиксельной точностью;
- шрифт: цвет, размер, тип, тень, жирность. в большинстве случаев от одного брейкпоинта к другому измеятся только жирность и размер шрифта;
- не нужно использовать два меню. Один список используется для всех брейкпоинтов, изменяется только его офоримление. (тут mobile first больше подойдет, т.к. проще добавлять свойства в класс, чем переопределять большую часть)

**Comment by DmitriyMK** [comment]
Спасибо большое за подробное описание проблемы, буду исправлять.

**Comment by DmitriyMK** [comment]
Сделано)) 
Единственное вопрос меня мучает. 
Подскажите, пожалуйста в мокапах блоки есть, в которых с уменьшением экрана, уменьшается и количество отображаемого контента (http://joxi.ru/J2bV89wh4e0Rl2). В таких случаях высоту задавать и скрывать через `overflow: hidden` ?
