### ISSUE TITLE
lesson 3

### ISSUE THREAD

**Issue by kateryna06** [DmitriyMK/DmitriyMK.github.io#2]
1. тег section http://joxi.ru/YxAeZwXhzydery может встретиться много раз на странице. По этому тут лучше использовать див с каким нибудь классом, например, wrapper 
2. неправильно задана ширина на этот section. Не нужно смешивать пиксели и проценты в верстке, если это не респонсив. У нас не респонсив, по этому все указывает в пикселях
3. свой блок ты не выровнял, я вроде как объясняла как это делать и у вас это было в уроке.
4. http://joxi.ru/XYmEldpI4XR0r6 эти блоки не по дизайну. Я просила чтоб на гитхаб вы заливали готовую работу, а не незаконченную. Если есть вопросы, то есть почта, скайп где можно задать вопросы и я отвечу.
5. логотип должен быть сделал ссылкой
6. http://prntscr.com/8yg9n2 если ты на обертку задаешь боковые отступы, которые отодвигают твои блоки от краев, то надочерние элементы не нужно добавлять еще раз отступ скраю. Если тебе нужен больше отступ, так добавь больше на родителя. Все правые отступы на меню, футере и контенте нужно убрать
7. http://joxi.ru/JMAjnDef6yM7Ae лишнее указание ширины. DIV у нас блочный элемент и занимает всю допустимую ширину. Если тебе она не нужна меньше, то и указывать ее не надо
8. http://joxi.ru/LVm6jE3fgnoMmZ это свойства для активного и ховерного состояния ссылки, а не для второго элемента
9. http://joxi.ru/48An1YNcZvl12O на body обычно задается font для твоего основного контента, т.е. для твоих параграфов. Тут он у тебя задан не правильно. Проверить все размеры шрифтов
10. http://joxi.ru/wGrq8DBheMaYAz вот какие свойства у тебя должны остаться на сайтбаре
11. http://joxi.ru/DBA0qJbCyjW9ry это у тебя актывная li Нужно добавить класс active и добавить паддинг не на li а на ссылку. И тогда у тебя отодвинется текст, а бордер останется на месте. Ты же бордер добавил на ссылку, а отступает от li
12. http://joxi.ru/Y82QJ14sQGO5Ad класс называем логически. У нас есть меню в котором не только будут велосипеды, но и другие товары. И там будет скорее всего таже структура, и будет не совсем правильно когда у нас останется класс bike а там будет картинка телефона.
13. http://joxi.ru/WL21gqJT7oYgrX ты задал такие свойства для параграфа. А на какой нибудь другой странице тебе тоже нужно добавить текст, и что у нас будет ? Беда получится, т.к. все эти стили у тебя применятся ко всем параграфам. И тебе придется или перебивать их или переделывать эти. Т.к. это у нас явно идет описание товара, то этот параграф нужно обернуть в какой нибудь див и задать на него отступы от верхнего блока. Чтоб когда ты сюда добавил еще один параграф у тебя все было хорошо
14. неправильный размер текста в футере. Не нужно лениться и не задавать фонт для текста
15. http://joxi.ru/lJ2bdoXFkaQKr6 это не пункт меню и его нужно вынести из ul
16. нужно добавить ховерное состояние для ссылок в футере
17. http://prntscr.com/8ygdk1 активная область должна быть только на тексте

**Comment by DmitriyMK** [comment]
Внес необходимые правки

**Comment by kateryna06** [comment]
1) у тебя на body никакой высоты и ширины не должно быть задано

убрано

2) уже говорила что на боди прописываем правильно font. C line-height чтоб потом не дописывать его для параграфов. Ищешь в дизайне параграфы смотришь какой у него font-size, line-height!!!! и font-family и все это прописываешь на body 

Прописал в body line-height общий 29px. Только на два параграфа поставил отдельный  line-height 27px и 31px. 

3) http://prntscr.com/90peph смотри какая большая активная область у твоего логотипа. А все потому что ты глобально для всех ссылок прописал display:block А это неправильно

Убрал общий display block. Оставил только  для aside li.

4) http://joxi.ru/L4AkXDEuWEe5rq это  можно записать в 1 строчку как margin: 40px 0; Если ты пишешь несколько значения для маржина или паддинга - пишем это в 1 строчку

Сделано. Так обычно стараюсь и делать.

5) http://joxi.ru/XEA40GbsLN9OAb что это за пустые теги?

Странно, у меня теги не пустые http://joxi.ru/Y2LYJywTyw4MA6

6) неправильная высота верхнего меню

Прописал в меню  height: 40px;  
Жуть какая-то получилась. Увидел что стоит -- display: inline-block; --, потому исправил на                                  line-height: 40px;  

7) когда делаю ховер в меню, то пункты прыгают, а должны стоять на месте

добавил в ли border-left: 1px solid transparent;  и border-right: 1px solid transparent; 
и уже не прыгают))

8) нужно добавить класс active в меню и прописать такие же стили как и ховер

Сделано.

9) http://joxi.ru/8ZrJxRjuqzo32j тут должен быть 1 бордер, а у тебя их 2

---

10) и цвет боредров в сайтбаре неправильный

Поменял на #c8c8c8. 

11) а где ховер для ссылок в сайтбаре?

Продублировал как и для active.

12) http://joxi.ru/JMAjnDefnKgOAe лишняя обертка

убрано

13) goods-image вот сюда нужно повесить бордер вокруг картинки и отступы, а каринку вырезать с нормальными размерами 

Фух, сделано. 

14) http://joxi.ru/DBA0qJbCG78zry эти отступы нужно повесить на сам див, а на параграфе отсавить маленький нижний отступ чтоб следующий параграф к нему не прилип

Сделано, все повесил на див goods-description 
Параграфу дал margin-bottom: 10px;

15) http://joxi.ru/XYmEldpIdz1er6 эта обертка лишняя 

Убрал.

16) у тебя в футере в меню так и осталась лишняя кликабельная область на ссылке. Область под и над ссылкой тоже кликабельна - должне быть только текст 

---

17) высота футера неправильная

Как и в случае с верхним меню прописал line-height: 40px;  

18) http://joxi.ru/L4AkXDEuWEpyrq эта обертка лишняя. Ты же можешь все эти стили повесить на footer 

Могу, но все эти обертки повесил (+в пункте 15), чтоб copyright от меню отделить с float по углам. Придумал новый способ)

**Comment by DmitriyMK** [comment]
6) неправильная высота верхнего меню

Прописал в меню height: 40px;
Жуть какая-то получилась (не по центру идет текст). 
 исправил на line-height: 40px;. - все красиво
А правильно ли я поступил?

9) http://joxi.ru/8ZrJxRjuqzo32j тут должен быть 1 бордер, а у тебя их 2

даю бордер на li, получается двойные бордеры. 
Дать на aside бордер и затем пошаманить над первыми 5 li нижний бордер?
Как то громоздко кажется?

16) у тебя в футере в меню так и осталась лишняя кликабельная область на ссылке. Область под и над ссылкой тоже кликабельна - должне быть только текст

не могу причину найти проблемы, отступов нет на ссылке. 

п.с В меню главном, область при наведении становится вот такой http://joxi.ru/DmBLOn9u9wqlAP что на макет не сильно похоже. 
добавить отступы на ссылку, то область кликательная увеличится. Как быть?

**Comment by kateryna06** [comment]
9) над нижним шаманить не надо. Боковые отступы задаешь на aside а как сделать горизонтальные бордеры подумай )) не надумаешь подскажу

Уря, фокус удался)

16) подсказываю http://joxi.ru/812MynxHpBvy2J 
 в верхнем меню и должна быть кликабельная область ))

и счастье было так близко))

**Comment by kateryna06** [comment]
1) http://joxi.ru/4vAWEqeu7Rj7mW что это такое??

2)  где активные состояния в менюшках?

3) http://joxi.ru/jnAylD6IZkXW2Z в дизайне есть отступы

4) цвет бордера неправильный

5) http://prntscr.com/92bstr не должно быть такого

6) http://joxi.ru/752aW9eH804xr0  а на боди зачем задавал line-height если ты его тут перебиваешь? 

7) http://joxi.ru/JMAjnDefzY45Ae а это что за кусок бордера?

8) http://prntscr.com/92btwf схлопнулся наш блок (((

**Comment by DmitriyMK** [comment]
1)  и  7)  - досадная опечатка;

2) Сделал для футера active. 

3) убрал padding: 0 35px; для menu li и вставил для menu li а;
Не получается сделать как на макете, чтоб каждый нечетный елемент имел отступ в ссылке 60рх; а четный 25px. Или этого делать не нужно?

4) поменял цвет бордера на #838383;

5) пришлось повозится немного, но  совет в скайпе помог справится с этим. Обернул боковое меню и контент в один див. Сайдбар влево, контент вправо, диву position: relative и overflow:hidden.  И никто никому не мешает)

6) потому что line-height для большинства элементов line-height 29px. Для текста в теге p (21рх) и менюшки боковой (37рх). Вот для них и сделал перебивку line-height.  http://joxi.ru/KAgo4kwf1MvaAl.
Так делать неправильно? В боди прописать правило только для основного контент? 

8) Не беда). Убрал свойство float:left с li и добавил для ul.

**Comment by kateryna06** [comment]
Так делать неправильно? В боди прописать правило только для основного контент? 

Ну вот сколько раз я вам про это писала в скайпе??? Миллион... уже буду злиться

1) на боди неправильный line-height!!!!!

2) http://joxi.ru/XYmEldpIgk9br6 где активный пункт меню?

3) при ховере должен быть градиент в меню а не просто заливка цветом 

4) http://joxi.ru/QY2L1ODcRXeWA6 эти 2 свойства лучше повесить на список

5) где активное состояние в сайтбаре?

6) http://joxi.ru/QeAO8x6hJREzro тебе тут картинку нужно выравнивать автоматически по центру, а не с помощью отступов

7) http://joxi.ru/8ZrJxRjuaOeX2j отступ прописываем просто для параграфа а не от родителя. Вот добавится где то еще параграфы и они слипнутся

**Comment by DmitriyMK** [comment]
Прошу понять и простить)
все сделано строго по пунктам, только лишь 
6) сделал text-align: center; но оставил паддинги для верха и низу. 
(способ сделать из класса .goods-image - display:table, и выровнять с помощью vertical-align: middle(предварительно указав высоту, не удались)
7) удалил его вообще. бо таинственным образом футер начал плясать из-за него.

**Comment by kateryna06** [comment]
1) вот так и не увидела активных состояний на странице (((

**Comment by kateryna06** [comment]
1) http://joxi.ru/752aW9eH8VzBr0  у тебя не должно быть этого пространства и при ховере бордеры должны будут накладываться один на другой

**Comment by DmitriyMK** [comment]
Активные состояния созданы и проблема с пустыми пространствами решена.

**Comment by kateryna06** [comment]
у тебя одни и теже стили для ховера и эктива почему ты не можешь написать 

.menu .active,
.menu a:hover{
bla bla bla
}

и при ховере у тебя дергаются пункты немного

**Comment by DmitriyMK** [comment]
стили обьеденил 
.menu a:active, .menu a:hover, .menu .active {
проблему с дерганием ховера решил изменением margin на margin-left: -1px;

**Comment by kateryna06** [comment]
ЗАЧЕТ
