### ISSUE TITLE
lesson 3 bonus

### ISSUE THREAD

**Issue by kateryna06** [DmitriyMK/DmitriyMK.github.io#3]
1) http://joxi.ru/1bmoyebHRl9XAy заешь что с ней делать?

2) http://prntscr.com/92bvfe беда с header не должен он у тебя светиться так. Отступы должны светиться отдельно от блока

3) http://joxi.ru/YxAeZwXh0VXBry пальма должна входить в одну картинку с логотипом, а не быть отдельно

4) убираем логотип с абсолюта

5) http://joxi.ru/8ZrJxRjuakna2j должен быть ссылко. Посмотри как нужно прописывать ссылки для имейлов

6) http://joxi.ru/WL21gqJTeDzzrX все figure в общий див

7) текст со страной тоже должен быть в сылке

8) рамку на картинке нужно сделать отдельно от картинки

**Comment by DmitriyMK** [comment]
1)  Кажись да. min-height?);
2)  есть.
3), 4) А я подумал раз в макете две картинки, то это задание попрактиковатся с абсолютом. Исправлено;
5) добавил mailto для емейла. Также добавлено active и hover.
Поизвращался с курсором)
6) сделано;
7) сделано
8) сделано.

п.с. я так смотрю есть тень внутренняя в рамках у картинок. 
но с генератором она не отображается. Хабрахабр советует вставить картинку как фон, и все будет ок. Мне для каждой страны див отдельный создавать? Или это сложный и нерациональный путь?

**Comment by DmitriyMK** [comment]
Сделано всё)

**Comment by kateryna06** [comment]
1) http://joxi.ru/0KAgRDJfozLo2l убираем с абсолюта

2) http://joxi.ru/qVrwGDeSZlxDrX страна должна быть в одной ссылке с картинкой

**Comment by DmitriyMK** [comment]
1) убраны все абсолюты. добавлены float;
2) ссылки подправлены;

**Comment by kateryna06** [comment]
ЗАЧЕТ
