### ISSUE TITLE
lesson 4

### ISSUE THREAD

**Issue by kateryna06** [DmitriyMK/DmitriyMK.github.io#4]
1) http://joxi.ru/brRqynCQQYbPA1 ну и для кого обсуждали в скайпе как нужно было делать этот бг? Тебе нужно было верезать однопиксельную по ширине и по всей длине картику и зарепитить ее по горизонтали и залить или нижним или верхним цветом

2) http://joxi.ru/1A5E0JuKKG36AE и когда ж я вас уже отучу ставить высоту на все попало. Ну вот не нужна она тебе тут. Высота ставится очень редко когда, в основном блоки должны тянуться по высоте.

3) http://joxi.ru/J2bdoXF44GNMr6 _blank ставится тогда на ссылку, когда она ведет на внешний источник. А логотип всегда должен вести на хоум

4) http://joxi.ru/eAO8x6h44pW5ro у тебя сейчас на странице 3 заголовка h1 а может быть только один

5) http://joxi.ru/823GM8S66DLn2O не нужен тебе тут такой большой отступ. Вернее тебе даже не нужен левый падинг

6) http://joxi.ru/Grq8DBhNNk98Az это должно быть сделано списком. И _blank тут со ссылок надо тоже поубирать

7) http://joxi.ru/gmvMDVhxxvWDra не должно быть тут отрицательных маржинов

8) http://joxi.ru/n2YpM0hjjZzPm6 а какой у нас должне быть синтаксис для бордера? http://htmlbook.ru/css/border

9) так, а ну быстро поубирать все _blank на ссылках!!!! я ж говорила в первом дз когда они ставятся

10) http://joxi.ru/L21gqJT66gbzrX таже беда с бордером

11) http://joxi.ru/E2p7DnUBBaPPmY не годится этот способ. У тебя блоки должны тянуться, а с высотой у тебя будет обрезаться текст. А ведь вам скидывали примеры!! ))

**Comment by DmitriyMK** [comment]
Исправлено все в лучшем виде убраны некрасивые моменты) 
Разве что по этим пунктам не до конца уверен что правильно:
7.) Помню что высоту на блок задавать это зло, но иначе отступ получается непонятный. - http://joxi.ru/MAjo4G6fvRPeOr
сделал так - .photo { height: 235px;}
11.) Не хотел создавать пустой див «centerColumn», но видимо придется.

**Comment by kateryna06** [comment]
1) http://joxi.ru/RmzjDQfWWaqymO что мешает повесить этот класс на список и избавиться от лишней обертки?

2) http://joxi.ru/L21gqJT66KeNrX ну это же заголовки!!!! 

3) http://joxi.ru/BA0qJbCBBEgnry бордери должны быть только там, где нарисовала стрелочки а не весь блок в бордере

4) http://joxi.ru/zAN7XBUllMb7r9 зачем тут clearfix??

**Comment by DmitriyMK** [comment]
исправлено все.
4) п.с странно, но при первоначальной версии версии дз, за блоки вылазили линии бордера. 
clearfix решал проблему данную. сейчас убрал, и все осталось на своих местах

**Comment by kateryna06** [comment]
1) бг не пофиксил, оно должно быть с шумом

2) http://joxi.ru/4AkXDEuMy05yrq лишние дивы

3) http://joxi.ru/823GM8S6JaX42O вот так должны быть разбиты ссылки

4) http://joxi.ru/MAjnDefv418qAe на эти ссылки на ховер должен убираться андерлайн, а не закрашиваться бг

5) http://joxi.ru/DmBK5RHNwgj02P по вертикали выровнять табличными свойствами

6) http://joxi.ru/RmzjDQfW0jO4mO это заголовок и убрать большой line-height

7) http://joxi.ru/VrwGDeSKOjaxrX по рукам буду бить за высоту!!!! Вот зачем ты туда ее ставишь?

8) http://joxi.ru/52aW9eHG4gB0r0 fieldset тут не нужен. Каждую строку нужно обернуть в див, на который будем задавать нижние отступы

9) http://joxi.ru/L21gqJT68znqrX неправильный цвет

10) http://joxi.ru/ZrJxRju19bR42j не кликается на лейбле чекбокс. Ты когда кликаешь на текст должен чекаться инпут

11) http://joxi.ru/krDaWkU0Egwdmp ширину убрать. Бг сделать градиентом. а не картинкой

12) добавить cursor:pointer на лейбел и кнопку

**Comment by DmitriyMK** [comment]
все исправлено и добавлено)

**Comment by sergolius** [comment]
1. http://joxi.ru/bmooBygCjMe4my
   a) заголовки должны быть жирными;
   b) линии не совпадают.
2. Пункты меню нужно выровнять по ширине.

**Comment by DmitriyMK** [comment]
1) Исправлено (минусовый маргин на div photo); 
2) Исправлено - в пунктах меню изменил отступы, и таким образом выравнял по ширине.;

**Comment by sergolius** [comment]
Почитайте о горизонтальном выравнивании элементов по ширине.

Зачет.
