### ISSUE TITLE
lesson 5

### ISSUE THREAD

**Issue by DmitriyMK** [DmitriyMK/DmitriyMK.github.io#5]

**Comment by DmitriyMK** [comment]
1) бг не пофиксил, оно должно быть с шумом

2) http://joxi.ru/4AkXDEuMy05yrq лишние дивы

3) http://joxi.ru/823GM8S6JaX42O вот так должны быть разбиты ссылки

4) http://joxi.ru/MAjnDefv418qAe на эти ссылки на ховер должен убираться андерлайн, а не закрашиваться бг

5) http://joxi.ru/DmBK5RHNwgj02P по вертикали выровнять табличными свойствами

6) http://joxi.ru/RmzjDQfW0jO4mO это заголовок и убрать большой line-height

7) http://joxi.ru/VrwGDeSKOjaxrX по рукам буду бить за высоту!!!! Вот зачем ты туда ее ставишь?

8) http://joxi.ru/52aW9eHG4gB0r0 fieldset тут не нужен. Каждую строку нужно обернуть в див, на который будем задавать нижние отступы

9) http://joxi.ru/L21gqJT68znqrX неправильный цвет

10) http://joxi.ru/ZrJxRju19bR42j не кликается на лейбле чекбокс. Ты когда кликаешь на текст должен чекаться инпут

11) http://joxi.ru/krDaWkU0Egwdmp ширину убрать. Бг сделать градиентом. а не картинкой

12) добавить cursor:pointer на лейбел и кнопку

**Comment by sergolius** [comment]
1. http://joxi.ru/Q2KnjkQC097Gmj
   Цвет текста не активных пункты должен быть голубым.
2. http://joxi.ru/GrqMV8ph8Njvrz
3. кнопки, линии у слова "OU" лучше сделать на css, вместо картинок;
4. выровнять ширину кнопок, линий, инпутов;
5. чекбокс у "Send" нужно выровнять по центру предложения "Send ..."
6. Попробуйте выровнять блок с формой через `position: absolute;`
7. Попробуйте избавиться от `display: table-cell;` на `.form {`
8. Попробуйте избавиться от скролла на странице. Только не за счет:

```
body {
    overflow: hidden;
}
```

**Comment by DmitriyMK** [comment]
1. Сделано;
2. Сделано;
3. добавил див line для линий у слова "OU", и сделал все через CSS; 
4. исправлена ширина инпутов и кнопок;
5. vertical-align сделал свое дело;
6. присвоен блоку с формой "position: absolute"  и  "wrapper: relative";
7. безболезненно избавился и от "display: table-cell; на .form {"  и  от  "display: table; " на wrapper. 
8. убрал сам скролл со страницы через ::-webkit-scrollbar {width: 0px;}

**Comment by sergolius** [comment]
1. http://joxi.ru/v29Q7bpIOZqG2G
   a) эти ссылки не должны подсвечиваться при наведении на них;
   b) эта кнопка сделана через картинку;
   c) попробуйте сделать эти линии без использования дополнительных элементов, а через
   http://htmlbook.ru/css/after http://htmlbook.ru/css/before
2. Скролл.
   Я имел ввиду не отображать скролл на это странице до тех пор, пока ее контент помещается в высоту одного окна.
   http://webbeaver.ru/future/viewport-unit/
3. http://joxi.ru/DmBX7KPijJBWAP
   "vertical-align": Выравнивает элемент по вертикали относительно своего родителя, окружающего текста или ячейки таблицы. (http://htmlbook.ru/css/vertical-align)
   По-этому его нужно добавить и на текст справа от чекбокса.

**Comment by DmitriyMK** [comment]
1.  http://joxi.ru/v29Q7bpIOZqG2G
      a) исправил;
      b) сверстал по новому;  
      // или ссылку-кнопку facebook как button сделать нужно было?//
      c) сделаны линии  border-bottom и border-top с помощью before и after; 
2.  Интересная статья, спасибо большое. возможен дурацкий вопрос( 
   Я должен пересчитать отступы на форме или шрифты под viewport-юниты?
3.  Спасибо, за замечания. Исправлено.

**Comment by sergolius** [comment]
1. В `body` вместо `min-height: 1024px;` использовать `min-height: 100vh;`
   Тогда `body` займет всю высоту окна. А если контента будет больше чем на одно окно - появится скролл.
2. Кнопка "Create my Account" должна быть с `type="submit"` для того, что по клику на ней она отправляла форму.
3. http://htmlbook.ru/html/input/name
   `input` которые несут в себе значение (value) должны иметь атрибут `name`.
   Это атрибут является ключем (как в объектах) под которым будет отправлено значение на сервер. Если его не прописать, то значение не будет отправлено. Обычно это цельная строка (без пробелом и спец. символов, допускаются тире "-" или нижнее подчеркивание "_" для разделения слов.

Зачет.

**Comment by DmitriyMK** [comment]
Исправлены замечания. 
Спасибо, буду знать)

**Comment by sergolius** [comment]
Запуште, если закончили правки.

**Comment by DmitriyMK** [comment]
Сорри. Уже залито с исправлениями

**Comment by sergolius** [comment]
Зачет.
