### ISSUE TITLE
js 1

### ISSUE THREAD

**Issue by sergolius** [DmitriyMK/DmitriyMK.github.io#6]
1. Степень может быть отрицательной: pow(2, -1); // 0.5

**Comment by DmitriyMK** [comment]
добавил проверку на отрицательную степень

**Comment by sergolius** [comment]
http://www.algebraclass.ru/otricatelnaya-stepen/

**Comment by sergolius** [comment]
Работу с отрицательной степенью добавите?

**Comment by DmitriyMK** [comment]
да, обязательно, надо же смыть позор с моей предыдущей проверки на отрицательную степень)). 
вечерком сделаю

**Comment by sergolius** [comment]
Какой будет результат, если возвести число "2" в степень "-2"? `alert(Math.pow(2, -2));`
http://www.algebraclass.ru/otricatelnaya-stepen/ в этой статье, можно найти как получить результат от отрицательной степени.

**Comment by DmitriyMK** [comment]
Простите за задержку, сделал)

проблема была в условии , если степень меньше нуля, то result = 1 / (result \* x), не срабатывала почему-то;
поставил в return = 1 / return

**Comment by sergolius** [comment]
Вы были близки!
Но отрицательная степень считается с ошибкой.
`Math.pow(2, -1);` // 0.5
`pow(2, -1);` // 1, ваш вариант
Ошибка кроется в `j < -1`.

**Comment by DmitriyMK** [comment]
Спасибо, исправил на j < 0

**Comment by sergolius** [comment]
Зачет.
