### ISSUE TITLE
js 2

### ISSUE THREAD

**Issue by sergolius** [DmitriyMK/DmitriyMK.github.io#7]
1. Добавить проверку, что бы пользователь не мог ввести пустые значения или отказаться от ввода. Если он отказался, прервать скрипт.

**Comment by DmitriyMK** [comment]
Сделал проверку чтоб при вводе пустого значения, прерывался скрипт.
    if (arr[i] === null || undefined);{
        return false;
    }
Так получилось, что при вводе любого значения скрипт прерывается.
подскажите в чем может быть ошибка?

**Comment by sergolius** [comment]
После изменений проверяйте работоспособность задания.
1. `if (arr[i] === null || undefined);{` - здесь две ошибки. одна логическая, вторая опечатка;
2. Вводим на последний запрос имени другое значение, его же вводим в запросе своего имени - не отработает.
Что бы было легче, вам лучше настроить подсветку синтаксиса для JS.

**Comment by DmitriyMK** [comment]
опечатка это (arr[j] = userName) которое должно быть  (arr[i] = userName). Исправил, теперь верно отрабатывает два одинаковых имени.
А вот скрипт прерываться все не хочет, при отмене ввода первого имени.
 при втором все удалось с помощью return false

**Comment by sergolius** [comment]
1. `if (arr[i] == null);{` - видите ";" ?
2. `if (arr[i] === userName){` - строка №17, когда выполнится это условие? чему равна переменная `i`, во время выполнения этого условия?
3. 
   `if (arr[i] === userName){` - это сравнение имен, следом за ней:
   `if (userName == null){` - проверка на отмену ввода имени.

**Comment by DmitriyMK** [comment]
1. спасибо, исправил;
2. условие выполнится если то имя что пользователь введет при первом prompt будет равно тому имени что введет при втором;
3. удалил лишнюю проверку;

Заработало)

**Comment by sergolius** [comment]
1. Для прерывания цикла предусмотрел `break;`
2. Проверяйте с максимально возможноным числом вариантов ввода имен пользователей, так и своего имени. Иногда для этого создают табличку, что бы было проще отмечать бажное поведение.
3. Сейчас делаем 5-ть "ок" подряд, а на вводе своего имени "отмена" - получаем 5-ть алертов о провале авторизации.
4. Еще было б не плохо добавить проверку на ввод пустого имени.

**Comment by sergolius** [comment]
Почти-почти.
1. Первое имя вводим пустым. Остальные оставляем стандартые. Пользователя почему-то не нашло. (['', 'Mickey', 'Mickey', 'Mickey', 'Mickey'])

**Comment by DmitriyMK** [comment]
Уря, проанализировал код, пересчитал скобки и нашел нестыковку, теперь работает)

и снова почти. 
Проверка на отмену ввода работает.
А на ввод пустых значений почему-то нет. Не могу понять почему.
Подскажите пожалуйста, в чем закралась ошибка
