### ISSUE TITLE
js 3-4

### ISSUE THREAD

**Issue by sergolius** [DmitriyMK/DmitriyMK.github.io#8]
1. Вместо `insertAdjacentElement` лучше использовать `parentNode.insertBefore`.
2. http://joxi.ru/l2Zv3zkTa8X72J
   Заголовок нужно выровнять.
   Поправить кнопку (текст).

**Comment by DmitriyMK** [comment]
1. сделано, использовал li.insertBefore(checkbox, label);
2. заголовок центрирован, текст на кнопке исправлен;

**Comment by sergolius** [comment]
Отилчно.
1. Проверяйте используемый функциона на кроссбраузерность (http://caniuse.com)
Есть есть желание, попробуйте сделать универсальное решения для добавления атрибутов для созданного элемента. (объект, обход объекта)

Зачет.
