### ISSUE TITLE
lesson 6

### ISSUE THREAD

**Issue by sergolius** [DmitriyMK/DmitriyMK.github.io#9]
1. http://joxi.ru/l2Zv3zkTa86G2J
2. выровнять элементы в верхнем меню;
3. шрифты не соответствуют исходнику;
4. выровнять кнопку "поиска".
5. http://joxi.ru/82QVWJKiZ1PGAd
   нужно выровнять изображения кружков в заголовках по вертикали, немного уменьшить высоту заголовков.
   a) подсвечиваться должен пункт на который навели мышку;
   b) нужно выровнять пункты и сделать кликабельным текст (изменять состояние чекбокса по клику на надпись);
   c) иконка/bullet активного меню должна становиться жирной как и текст.

**Comment by DmitriyMK** [comment]
1. http://joxi.ru/l2Zv3zkTa86G2J
2. подправил элементы;
3. исправил на исходный "Arial Black";
4. кнопку поиска, выровнял. 
5. красота наведена
   a) сделано;
   b) пункты выровнял, текст в чекбоксах кликабельный;
   c) не могу сделать иконку жирной при наведении. (
   Иконку вставлял через псевдоелемент left_aside li:before.

**Comment by sergolius** [comment]
1. .enter-menu - height: 26px
   .login_password input - height: 18px
   (26 - 18) / 2 = 4 (px)
2. http://joxi.ru/12M1Vy6h7lGD2J
   a) png формат изображения используется, что бы сделать часть изображения прозрачным. в остальных случая можно использовать jpg. ваши иконки не прозрачны, по-этому перекрывают границы/бордеры;
   b) нужно выровнять вертикально иконку и текст, увеличить скругление углов;
   c) ширина всех трех колонок должна быть одинакова. нужно скруглить углы на элементе содержащем фон колонок;
   d) иконка/bullet активного пункта должен изменяться как и текст. эту же иконку нужно поднять на 1px для вертикального выравнивания.

**Comment by DmitriyMK** [comment]
.enter-menu - height: 26px
.login_password input - height: 18px
(26 - 18) / 2 = 4 (px)
Я так понял это значение отступов у инпута
http://joxi.ru/YmEax8wTZ6pXom

http://joxi.ru/12M1Vy6h7lGD2J
a) исправил, получше вырезал иконки.
b) сделано;
c) сделал общие отступы между картинками, и внутри картинок.
углы также скруглил;
d) изменил немного стили, вырезал иконку новую из макета и удалось исправить, уря:)

**Comment by sergolius** [comment]
1. http://joxi.ru/12M1Vy6h7lGD2J
   b) нужно скруглить углы, уменьшить левый и нижний отступ от иконки.

Зачет.
